name: Pest Tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/pest.yml'

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Create database.sqlite file and copy env file
        run: |-
          touch database/database.sqlite
          cp .env.example .env

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-scripts"

      - name: Run Pest
        run: |-
          php artisan key:generate
          ./vendor/bin/pest
